services:
  - type: web
    name: sfcollab-backend
    env: node
    plan: free
    autoDeploy: true
    branch: main
    buildCommand: "npm install"
    startCommand: "npm start"
    healthCheckPath: "/health"
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: RATE_LIMIT_WINDOW_MS
        value: "900000"
      - key: RATE_LIMIT_MAX_REQUESTS
        value: "100"
      # Optional: set allowed origins for CORS in production, comma-separated
      # and update server.js to read this if you choose to use it
      # - key: ALLOWED_ORIGINS
      #   value: "https://your-frontend.onrender.com"
    


